Repository team9502/sinchulgwinong-BE, pull requests merged in 2024-06, with the labels that each got.

#3 feat: 회원가입
  build.gradle
  src/main/java/team9502/sinchulgwinong/domain/auth/controller/AuthController.java
  src/main/java/team9502/sinchulgwinong/domain/auth/dto/request/UserLoginRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/auth/dto/request/UserSignupRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/auth/service/AuthService.java
  src/main/java/team9502/sinchulgwinong/domain/user/entity/User.java
  src/main/java/team9502/sinchulgwinong/domain/user/enums/LoginType.java
  src/main/java/team9502/sinchulgwinong/domain/user/enums/Role.java
  src/main/java/team9502/sinchulgwinong/domain/user/repository/UserRepository.java
  src/main/java/team9502/sinchulgwinong/global/config/CorsConfig.java
  src/main/java/team9502/sinchulgwinong/global/config/JpaConfig.java
  src/main/java/team9502/sinchulgwinong/global/config/RestTemplateConfig.java
  src/main/java/team9502/sinchulgwinong/global/config/SwaggerConfig.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
  src/main/java/team9502/sinchulgwinong/global/entity/BaseTimeEntity.java
  src/main/java/team9502/sinchulgwinong/global/exception/AccessDeniedHandlerImpl.java
  src/main/java/team9502/sinchulgwinong/global/exception/ApiException.java
  src/main/java/team9502/sinchulgwinong/global/exception/ErrorCode.java
  src/main/java/team9502/sinchulgwinong/global/exception/GlobalExceptionHandler.java
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthorizationFilter.java
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtTokenProvider.java
  src/main/java/team9502/sinchulgwinong/global/response/GlobalApiResponse.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
  src/main/java/team9502/sinchulgwinong/global/security/UserDetailsImpl.java
  src/main/java/team9502/sinchulgwinong/global/security/UserDetailsServiceImpl.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: enhancement

#6 [기능 추가 및 개선] 로그인 기능, 응답 코드 제거, 회원가입 예외 처리 추가
  src/main/java/team9502/sinchulgwinong/domain/auth/controller/AuthController.java
  src/main/java/team9502/sinchulgwinong/domain/auth/controller/BusinessInfoController.java
  src/main/java/team9502/sinchulgwinong/domain/auth/dto/request/BusinessStatusRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/auth/dto/request/BusinessVerificationRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/auth/dto/request/UserSignupRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/auth/dto/response/UserLoginResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/auth/service/AuthService.java
  src/main/java/team9502/sinchulgwinong/domain/auth/service/BusinessInfoService.java
  src/main/java/team9502/sinchulgwinong/domain/user/entity/User.java
  src/main/java/team9502/sinchulgwinong/domain/user/enums/Role.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
  src/main/java/team9502/sinchulgwinong/global/exception/AccessDeniedHandlerImpl.java
  src/main/java/team9502/sinchulgwinong/global/exception/ApiException.java
  src/main/java/team9502/sinchulgwinong/global/exception/ErrorCode.java
  src/main/java/team9502/sinchulgwinong/global/exception/GlobalExceptionHandler.java
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthorizationFilter.java
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtTokenProvider.java
  src/main/java/team9502/sinchulgwinong/global/response/GlobalApiResponse.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: enhancement

#10 사업자 번호 암호화 및 구인자 회원가입 기능 추가
  build.gradle
  src/main/java/team9502/sinchulgwinong/domain/auth/controller/AuthController.java
  src/main/java/team9502/sinchulgwinong/domain/auth/controller/BusinessInfoController.java
  src/main/java/team9502/sinchulgwinong/domain/auth/dto/request/CpUserSignupRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/auth/service/AuthService.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/entity/CompanyUser.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/repository/CompanyUserRepository.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/service/EncryptionService.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: enhancement

#12 feat: 기업회원(구인자) 로그인
  src/main/java/team9502/sinchulgwinong/domain/auth/controller/AuthController.java
  src/main/java/team9502/sinchulgwinong/domain/auth/dto/request/CompanyUserLoginRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/auth/dto/response/CompanyUserLoginResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/auth/service/AuthService.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
  src/main/java/team9502/sinchulgwinong/global/security/UserDetailsImpl.java
  src/main/java/team9502/sinchulgwinong/global/security/UserDetailsServiceImpl.java
Labels: enhancement

#14 Feature/point 포인트 설정
  src/main/java/team9502/sinchulgwinong/domain/point/entity/Point.java
  src/main/java/team9502/sinchulgwinong/domain/point/entity/SavedPoint.java
  src/main/java/team9502/sinchulgwinong/domain/point/entity/UsedPoint.java
  src/main/java/team9502/sinchulgwinong/domain/point/enums/SpType.java
  src/main/java/team9502/sinchulgwinong/domain/point/enums/UpType.java
Labels: enhancement

#18 feature: 게시글 CRUD 구현
  src/main/java/team9502/sinchulgwinong/domain/board/controller/BoardController.java
Labels: enhancement

#19 hotfix: 헤더 수정
  src/main/java/team9502/sinchulgwinong/global/config/CorsConfig.java
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: enhancement

#20 hotfix: 유저 정보 추출
  src/main/java/team9502/sinchulgwinong/global/security/UserDetailsImpl.java
  src/main/java/team9502/sinchulgwinong/global/security/UserDetailsServiceImpl.java
Labels: enhancement

#21 hotfix: security에 filter 수정
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
Labels: enhancement

#22 fix: UserDetailsImpl를 사용하여 user 정보를 받아오도록 수정
  src/main/java/team9502/sinchulgwinong/domain/board/controller/BoardController.java
  src/main/java/team9502/sinchulgwinong/domain/board/service/BoardService.java
Labels: documentation

#25 fix: 게시글 Mapping 수정, 필요없는 필드 삭제
  src/main/java/team9502/sinchulgwinong/domain/board/controller/BoardController.java
  src/main/java/team9502/sinchulgwinong/domain/board/dto/request/BoardRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/board/entity/Board.java
  src/main/java/team9502/sinchulgwinong/domain/board/service/BoardService.java
Labels: fix

#24 feature: 댓글 CRUD 구현
  src/main/java/team9502/sinchulgwinong/domain/comment/controller/CommentController.java
  src/main/java/team9502/sinchulgwinong/domain/comment/dto/request/CommentRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/comment/dto/response/CommentResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/comment/entity/Comment.java
  src/main/java/team9502/sinchulgwinong/domain/comment/repository/CommentRepository.java
  src/main/java/team9502/sinchulgwinong/domain/comment/service/CommentService.java
  src/main/java/team9502/sinchulgwinong/global/exception/ErrorCode.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
Labels: enhancement

#27 fix: 변수명 수정
  src/main/java/team9502/sinchulgwinong/domain/board/dto/request/BoardRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/board/entity/Board.java
  src/main/java/team9502/sinchulgwinong/domain/board/service/BoardService.java
Labels: fix

#28 fix: object 수정
  src/main/java/team9502/sinchulgwinong/domain/comment/controller/CommentController.java
  src/main/java/team9502/sinchulgwinong/domain/comment/entity/Comment.java
Labels: fix

#26 feat: 리뷰 생성 & 회원가입시 포인트 적립
  .gitignore
  src/main/java/team9502/sinchulgwinong/domain/auth/service/AuthService.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/entity/CompanyUser.java
  src/main/java/team9502/sinchulgwinong/domain/point/CommonPoint.java
  src/main/java/team9502/sinchulgwinong/domain/point/entity/Point.java
  src/main/java/team9502/sinchulgwinong/domain/point/repository/PointRepository.java
  src/main/java/team9502/sinchulgwinong/domain/point/repository/SavedPointRepository.java
  src/main/java/team9502/sinchulgwinong/domain/point/repository/UsedPointRepository.java
  src/main/java/team9502/sinchulgwinong/domain/point/service/PointService.java
  src/main/java/team9502/sinchulgwinong/domain/review/controller/ReviewController.java
  src/main/java/team9502/sinchulgwinong/domain/review/dto/request/ReviewCreationRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/review/dto/response/ReviewCreationResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/review/entity/Review.java
  src/main/java/team9502/sinchulgwinong/domain/review/repository/ReviewRepository.java
  src/main/java/team9502/sinchulgwinong/domain/review/service/ReviewService.java
  src/main/java/team9502/sinchulgwinong/domain/user/entity/User.java
  src/main/java/team9502/sinchulgwinong/global/exception/ErrorCode.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
  src/main/java/team9502/sinchulgwinong/global/security/UserDetailsImpl.java
Labels: enhancement

#31 fix: fetchtype 수정
  src/main/java/team9502/sinchulgwinong/domain/user/entity/User.java
Labels: fix

#32 fix: 게시글 작성시 포인트 적립 되도록 수정
  src/main/java/team9502/sinchulgwinong/domain/board/service/BoardService.java
Labels: fix

#37 fix: readOnly = true 추가
  src/main/java/team9502/sinchulgwinong/domain/board/service/BoardService.java
Labels: fix

#38 feat: 기업회원 리뷰 전체 조회
  src/main/java/team9502/sinchulgwinong/domain/review/controller/ReviewController.java
  src/main/java/team9502/sinchulgwinong/domain/review/dto/response/ReviewListResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/review/dto/response/ReviewResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/review/repository/ReviewRepository.java
  src/main/java/team9502/sinchulgwinong/domain/review/service/ReviewService.java
  src/main/java/team9502/sinchulgwinong/global/exception/ErrorCode.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
  src/main/java/team9502/sinchulgwinong/global/security/UserDetailsImpl.java
Labels: enhancement

#40 fix: 환경 변수 명 수정
  src/main/resources/application-prod.yml
Labels: fix

#41 fix: 환경 변수 명 수정
  src/main/resources/application-prod.yml
Labels: fix

#43 Update sinChul.yml
  .github/workflows/sinChul.yml
Labels: deployment

#44 feature: test를 위한 api 생성
  src/main/java/team9502/sinchulgwinong/domain/aws/awsTest.java
Labels: deployment

#45 feature: test를 위한 api 생성
  src/main/java/team9502/sinchulgwinong/domain/aws/awsTest.java
Labels: deployment

#47 fix: test를 위한 수정
  src/main/java/team9502/sinchulgwinong/domain/aws/awsTest.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
Labels: deployment

#48 fix: test를 위한 수정
  src/main/java/team9502/sinchulgwinong/domain/aws/awsTest.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
Labels: deployment

#49 Update sinChul.yml
  .github/workflows/sinChul.yml
Labels: deployment

#50 Update sinChul.yml
  .github/workflows/sinChul.yml
Labels: deployment

#52 fix: 소문자로 설정 되어있던 환경 변수 수정
  src/main/resources/application-prod.yml
Labels: deployment

#53 fix: 소문자로 설정 되어있던 환경 변수 수정
  .github/workflows/sinChul.yml
  src/main/resources/application-prod.yml
Labels: deployment

#46 feat: 리뷰 열람&조회 + QueryDSL과 페이지네이션
  .gitignore
  build.gradle
  src/main/generated/team9502/sinchulgwinong/domain/board/entity/QBoard.java
  src/main/generated/team9502/sinchulgwinong/domain/comment/entity/QComment.java
  src/main/generated/team9502/sinchulgwinong/domain/companyUser/entity/QCompanyUser.java
  src/main/generated/team9502/sinchulgwinong/domain/point/entity/QPoint.java
  src/main/generated/team9502/sinchulgwinong/domain/point/entity/QSavedPoint.java
  src/main/generated/team9502/sinchulgwinong/domain/point/entity/QUsedPoint.java
  src/main/generated/team9502/sinchulgwinong/domain/review/entity/QReview.java
  src/main/generated/team9502/sinchulgwinong/domain/review/entity/QUserReviewStatus.java
  src/main/generated/team9502/sinchulgwinong/domain/scrap/entity/QScrap.java
  src/main/generated/team9502/sinchulgwinong/domain/user/entity/QUser.java
  src/main/generated/team9502/sinchulgwinong/global/entity/QBaseTimeEntity.java
  src/main/java/team9502/sinchulgwinong/domain/review/controller/ReviewController.java
  src/main/java/team9502/sinchulgwinong/domain/review/dto/response/UserReviewListResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/review/dto/response/UserReviewResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/review/entity/UserReviewStatus.java
  src/main/java/team9502/sinchulgwinong/domain/review/repository/ReviewRepository.java
  src/main/java/team9502/sinchulgwinong/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/team9502/sinchulgwinong/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/team9502/sinchulgwinong/domain/review/repository/UserReviewStatusRepository.java
  src/main/java/team9502/sinchulgwinong/domain/review/service/ReviewService.java
  src/main/java/team9502/sinchulgwinong/global/config/QueryDslConfig.java
  src/main/java/team9502/sinchulgwinong/global/exception/ErrorCode.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
Labels: enhancement

#54 feat: 포인트 총액 조회
  src/main/java/team9502/sinchulgwinong/domain/point/controller/PointController.java
  src/main/java/team9502/sinchulgwinong/domain/point/dto/response/PointSummaryResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/point/repository/SavedPointRepository.java
  src/main/java/team9502/sinchulgwinong/domain/point/repository/UsedPointRepository.java
  src/main/java/team9502/sinchulgwinong/domain/point/service/PointService.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
Labels: enhancement

#59 feature: 구인 게시글 CRUD 구현
  build.gradle
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/controller/JobBoardController.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/request/JobBoardRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/response/JobBoardResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/entity/BoardImage.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/entity/JobBoard.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/entity/JobStatus.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/entity/SalaryType.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/repository/BoardImageRepository.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/repository/JobBoardRepository.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardService.java
  src/main/java/team9502/sinchulgwinong/global/config/S3Config.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: enhancement

#61 deployment
  .github/workflows/sinChul.yml
  .gitignore
  build.gradle
  src/main/generated/team9502/sinchulgwinong/domain/board/entity/QBoard.java
  src/main/generated/team9502/sinchulgwinong/domain/comment/entity/QComment.java
  src/main/generated/team9502/sinchulgwinong/domain/companyUser/entity/QCompanyUser.java
  src/main/generated/team9502/sinchulgwinong/domain/point/entity/QPoint.java
  src/main/generated/team9502/sinchulgwinong/domain/point/entity/QSavedPoint.java
  src/main/generated/team9502/sinchulgwinong/domain/point/entity/QUsedPoint.java
  src/main/generated/team9502/sinchulgwinong/domain/review/entity/QReview.java
  src/main/generated/team9502/sinchulgwinong/domain/review/entity/QUserReviewStatus.java
  src/main/generated/team9502/sinchulgwinong/domain/scrap/entity/QScrap.java
  src/main/generated/team9502/sinchulgwinong/domain/user/entity/QUser.java
  src/main/generated/team9502/sinchulgwinong/global/entity/QBaseTimeEntity.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/controller/JobBoardController.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/request/JobBoardRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/response/JobBoardResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/entity/BoardImage.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/entity/JobBoard.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/entity/JobStatus.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/entity/SalaryType.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/repository/BoardImageRepository.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/repository/JobBoardRepository.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardService.java
  src/main/java/team9502/sinchulgwinong/domain/point/controller/PointController.java
  src/main/java/team9502/sinchulgwinong/domain/point/dto/response/PointSummaryResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/point/dto/response/SavedPointDetailResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/point/repository/SavedPointRepository.java
  src/main/java/team9502/sinchulgwinong/domain/point/repository/SavedPointRepositoryCustom.java
  src/main/java/team9502/sinchulgwinong/domain/point/repository/SavedPointRepositoryCustomImpl.java
  src/main/java/team9502/sinchulgwinong/domain/point/repository/UsedPointRepository.java
  src/main/java/team9502/sinchulgwinong/domain/point/service/PointService.java
  src/main/java/team9502/sinchulgwinong/domain/review/controller/ReviewController.java
  src/main/java/team9502/sinchulgwinong/domain/review/dto/response/UserReviewListResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/review/dto/response/UserReviewResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/review/entity/UserReviewStatus.java
  src/main/java/team9502/sinchulgwinong/domain/review/repository/ReviewRepository.java
  src/main/java/team9502/sinchulgwinong/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/team9502/sinchulgwinong/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/team9502/sinchulgwinong/domain/review/repository/UserReviewStatusRepository.java
  src/main/java/team9502/sinchulgwinong/domain/review/service/ReviewService.java
  src/main/java/team9502/sinchulgwinong/global/config/QueryDslConfig.java
  src/main/java/team9502/sinchulgwinong/global/config/S3Config.java
  src/main/java/team9502/sinchulgwinong/global/config/SwaggerConfig.java
  src/main/java/team9502/sinchulgwinong/global/exception/ErrorCode.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: deployment

#62 Update sinChul.yml
  .github/workflows/sinChul.yml
Labels: deployment

#75 Update sinChul.yml
  .github/workflows/sinChul.yml
Labels: deployment

#76 fix: Get 방식 게시글 조회 인증 예외처리
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/controller/JobBoardController.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardService.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
Labels: fix

#81 feat: 사용자&기업(회원) 프로필 조회와 프로필 수정
  src/main/java/team9502/sinchulgwinong/domain/companyUser/controller/CpUserController.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/dto/request/CpUserProfileUpdateRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/dto/response/CpUserProfileResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/entity/CompanyUser.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/service/CpUserService.java
  src/main/java/team9502/sinchulgwinong/domain/user/controller/UserController.java
  src/main/java/team9502/sinchulgwinong/domain/user/dto/request/UserProfileUpdateRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/user/dto/response/UserProfileResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/user/entity/User.java
  src/main/java/team9502/sinchulgwinong/domain/user/service/UserService.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
Labels: enhancement

#77 feat: 포인트 사용 내역 조회 + 페이지네이션(무한스크롤) 적용
  src/main/java/team9502/sinchulgwinong/domain/point/controller/PointController.java
  src/main/java/team9502/sinchulgwinong/domain/point/dto/response/UsedPointDetailResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/point/repository/UsedPointRepository.java
  src/main/java/team9502/sinchulgwinong/domain/point/repository/UsedPointRepositoryCustom.java
  src/main/java/team9502/sinchulgwinong/domain/point/repository/UsedPointRepositoryCustomImpl.java
  src/main/java/team9502/sinchulgwinong/domain/point/service/PointService.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
Labels: enhancement

#84 feat: 포인트 사용 내역 조회시 페이지네이션(무한스크롤) 적용 & 프로필 조회 & 프로필 변경
  src/main/java/team9502/sinchulgwinong/domain/companyUser/controller/CpUserController.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/dto/request/CpUserProfileUpdateRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/dto/response/CpUserProfileResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/entity/CompanyUser.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/service/CpUserService.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/controller/JobBoardController.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardService.java
  src/main/java/team9502/sinchulgwinong/domain/point/controller/PointController.java
  src/main/java/team9502/sinchulgwinong/domain/point/dto/response/UsedPointDetailResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/point/repository/UsedPointRepository.java
  src/main/java/team9502/sinchulgwinong/domain/point/repository/UsedPointRepositoryCustom.java
  src/main/java/team9502/sinchulgwinong/domain/point/repository/UsedPointRepositoryCustomImpl.java
  src/main/java/team9502/sinchulgwinong/domain/point/service/PointService.java
  src/main/java/team9502/sinchulgwinong/domain/user/controller/UserController.java
  src/main/java/team9502/sinchulgwinong/domain/user/dto/request/UserProfileUpdateRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/user/dto/response/UserProfileResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/user/entity/User.java
  src/main/java/team9502/sinchulgwinong/domain/user/service/UserService.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
Labels: enhancement

#85 feat: 사용자/기업회원 비밀번호 수정
  src/main/java/team9502/sinchulgwinong/domain/companyUser/controller/CpUserController.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/dto/request/CpUserPasswordUpdateRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/entity/CompanyUser.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/service/CpUserService.java
  src/main/java/team9502/sinchulgwinong/domain/user/controller/UserController.java
  src/main/java/team9502/sinchulgwinong/domain/user/dto/request/UserPasswordUpdateRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/user/entity/User.java
  src/main/java/team9502/sinchulgwinong/domain/user/service/UserService.java
  src/main/java/team9502/sinchulgwinong/global/exception/ErrorCode.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
  src/main/java/team9502/sinchulgwinong/global/security/UserDetailsImpl.java
  src/main/java/team9502/sinchulgwinong/global/security/UserDetailsServiceImpl.java
Labels: enhancement

#91 feat: 리뷰 조회시 현재 페이지 번호와 전체 페이지 수 응답값에 포함 + 공개된 리뷰 최상단
  src/main/java/team9502/sinchulgwinong/domain/review/dto/response/UserReviewListResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/review/repository/ReviewRepositoryImpl.java
Labels: enhancement

#89 feat: 기업(회원) 프로필 조회시 평점 평균 추가
  src/main/java/team9502/sinchulgwinong/domain/companyUser/controller/CpUserController.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/dto/response/CpUserProfileResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/entity/CompanyUser.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/service/CpUserService.java
  src/main/java/team9502/sinchulgwinong/domain/review/service/ReviewService.java
Labels: enhancement

#88 feat: 포인트 총액 내역 조회시 다음 페이지 여부 추가
  src/main/java/team9502/sinchulgwinong/domain/point/controller/PointController.java
  src/main/java/team9502/sinchulgwinong/domain/point/dto/response/PagedResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/point/service/PointService.java
Labels: enhancement

#93 feat: 사용자/기업(회원) 비밀번호 수정 + 포인트 총액 내역 조회시 다음 페이지 여부 추가 + 리뷰 조회시 현재 페이지 번호와 전체 페이지 수 응답값에 포함 + 리뷰 조회시 공개된 리뷰가 최상단으로 오게 수정
  src/main/java/team9502/sinchulgwinong/domain/companyUser/controller/CpUserController.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/dto/request/CpUserPasswordUpdateRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/dto/response/CpUserProfileResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/entity/CompanyUser.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/service/CpUserService.java
  src/main/java/team9502/sinchulgwinong/domain/point/controller/PointController.java
  src/main/java/team9502/sinchulgwinong/domain/point/dto/response/PagedResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/point/service/PointService.java
  src/main/java/team9502/sinchulgwinong/domain/review/dto/response/UserReviewListResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/team9502/sinchulgwinong/domain/review/service/ReviewService.java
  src/main/java/team9502/sinchulgwinong/domain/user/controller/UserController.java
  src/main/java/team9502/sinchulgwinong/domain/user/dto/request/UserPasswordUpdateRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/user/entity/User.java
  src/main/java/team9502/sinchulgwinong/domain/user/service/UserService.java
  src/main/java/team9502/sinchulgwinong/global/exception/ErrorCode.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
  src/main/java/team9502/sinchulgwinong/global/security/UserDetailsImpl.java
  src/main/java/team9502/sinchulgwinong/global/security/UserDetailsServiceImpl.java
Labels: enhancement

#94 feat: 이메일 인증&검증
  .github/workflows/sinChul.yml
  src/main/java/team9502/sinchulgwinong/domain/auth/controller/AuthController.java
  src/main/java/team9502/sinchulgwinong/domain/auth/service/AuthService.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/controller/CpUserController.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/service/CpUserService.java
  src/main/java/team9502/sinchulgwinong/domain/email/controller/EmailVerificationController.java
  src/main/java/team9502/sinchulgwinong/domain/email/dto/request/EmailVerificationCodeRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/email/dto/request/EmailVerificationRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/email/entity/EmailVerifications.java
  src/main/java/team9502/sinchulgwinong/domain/email/enums/UserType.java
  src/main/java/team9502/sinchulgwinong/domain/email/enums/VerificationStatus.java
  src/main/java/team9502/sinchulgwinong/domain/email/repository/EmailVerificationRepository.java
  src/main/java/team9502/sinchulgwinong/domain/email/service/EmailService.java
  src/main/java/team9502/sinchulgwinong/domain/email/service/EmailServiceImpl.java
  src/main/java/team9502/sinchulgwinong/domain/email/service/EmailVerificationService.java
  src/main/java/team9502/sinchulgwinong/domain/user/controller/UserController.java
  src/main/java/team9502/sinchulgwinong/domain/user/service/UserService.java
  src/main/java/team9502/sinchulgwinong/global/config/MailConfig.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
  src/main/java/team9502/sinchulgwinong/global/exception/ErrorCode.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: enhancement, fix

#100 feat: 이메일 인증&검증 + 회원가입/프로필 수정시 이메일 인증&검증 추가
  .github/workflows/sinChul.yml
  src/main/java/team9502/sinchulgwinong/domain/auth/controller/AuthController.java
  src/main/java/team9502/sinchulgwinong/domain/auth/service/AuthService.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/controller/CpUserController.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/service/CpUserService.java
  src/main/java/team9502/sinchulgwinong/domain/email/controller/EmailVerificationController.java
  src/main/java/team9502/sinchulgwinong/domain/email/dto/request/EmailVerificationCodeRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/email/dto/request/EmailVerificationRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/email/entity/EmailVerifications.java
  src/main/java/team9502/sinchulgwinong/domain/email/enums/UserType.java
  src/main/java/team9502/sinchulgwinong/domain/email/enums/VerificationStatus.java
  src/main/java/team9502/sinchulgwinong/domain/email/repository/EmailVerificationRepository.java
  src/main/java/team9502/sinchulgwinong/domain/email/service/EmailService.java
  src/main/java/team9502/sinchulgwinong/domain/email/service/EmailServiceImpl.java
  src/main/java/team9502/sinchulgwinong/domain/email/service/EmailVerificationService.java
  src/main/java/team9502/sinchulgwinong/domain/user/controller/UserController.java
  src/main/java/team9502/sinchulgwinong/domain/user/service/UserService.java
  src/main/java/team9502/sinchulgwinong/global/config/MailConfig.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
  src/main/java/team9502/sinchulgwinong/global/exception/ErrorCode.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: enhancement, fix

#101 feat: 로그인 없이 기업(회원) 프로필 조회 가능 + 구글 로그인
  build.gradle
  src/main/java/team9502/sinchulgwinong/domain/auth/dto/request/CpUserSignupRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/auth/dto/request/UserSignupRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/auth/dto/response/UserLoginResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/auth/service/AuthService.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/controller/CpUserController.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/service/CpUserService.java
  src/main/java/team9502/sinchulgwinong/domain/oauth/controller/SocialLoginController.java
  src/main/java/team9502/sinchulgwinong/domain/oauth/enums/SocialType.java
  src/main/java/team9502/sinchulgwinong/domain/oauth/security/CustomOauth2UserDetails.java
  src/main/java/team9502/sinchulgwinong/domain/oauth/security/CustomOauth2UserService.java
  src/main/java/team9502/sinchulgwinong/domain/oauth/security/GoogleUserDetails.java
  src/main/java/team9502/sinchulgwinong/domain/oauth/security/OAuth2UserInfo.java
  src/main/java/team9502/sinchulgwinong/domain/oauth/service/SocialLoginService.java
  src/main/java/team9502/sinchulgwinong/domain/user/entity/User.java
  src/main/java/team9502/sinchulgwinong/domain/user/enums/LoginType.java
  src/main/java/team9502/sinchulgwinong/domain/user/service/UserService.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
  src/main/java/team9502/sinchulgwinong/global/exception/ErrorCode.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
  src/main/java/team9502/sinchulgwinong/global/security/UserDetailsImpl.java
  src/main/java/team9502/sinchulgwinong/global/security/UserDetailsServiceImpl.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: enhancement

#105 fix: swagger 수정
  src/main/java/team9502/sinchulgwinong/domain/auth/controller/AuthController.java
  src/main/java/team9502/sinchulgwinong/domain/auth/dto/request/CompanyUserLoginRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/auth/dto/request/UserLoginRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/auth/service/AuthService.java
  src/main/java/team9502/sinchulgwinong/global/exception/ErrorCode.java
Labels: fix

#106 fix: swagger 수정
  src/main/java/team9502/sinchulgwinong/domain/point/controller/PointController.java
Labels: fix

#107 fix: swagger 수정
  src/main/java/team9502/sinchulgwinong/domain/review/controller/ReviewController.java
Labels: fix

#108 fix: swagger 수정
  src/main/java/team9502/sinchulgwinong/domain/companyUser/controller/CpUserController.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/dto/request/CpUserPasswordUpdateRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/user/controller/UserController.java
  src/main/java/team9502/sinchulgwinong/domain/user/dto/response/UserProfileResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/user/service/UserService.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
Labels: enhancement, fix

#111 feat: 포인트 적립 타입 추가
  src/main/java/team9502/sinchulgwinong/domain/point/enums/SpType.java
  src/main/java/team9502/sinchulgwinong/domain/point/service/PointService.java
Labels: enhancement

#109 fix: 내가 작성한 댓글 전체 조회 api 생성, 전체 조회 응답 수정
  src/main/java/team9502/sinchulgwinong/domain/comment/controller/CommentController.java
  src/main/java/team9502/sinchulgwinong/domain/comment/dto/response/CommentResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/comment/entity/Comment.java
  src/main/java/team9502/sinchulgwinong/domain/comment/repository/CommentRepository.java
  src/main/java/team9502/sinchulgwinong/domain/comment/service/CommentService.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
Labels: fix

#113 fix: 게시글 전체 조회시 총 개수 응답 하도록 수정, 내가 작성한 게시글 전체 조회 api 구현
  src/main/java/team9502/sinchulgwinong/domain/board/controller/BoardController.java
  src/main/java/team9502/sinchulgwinong/domain/board/dto/response/BoardListResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/board/entity/Board.java
  src/main/java/team9502/sinchulgwinong/domain/board/repository/BoardRepository.java
  src/main/java/team9502/sinchulgwinong/domain/board/service/BoardService.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
Labels: fix

#114 fix: 보드 전체 조회 응답값 수정
  src/main/java/team9502/sinchulgwinong/domain/comment/controller/CommentController.java
  src/main/java/team9502/sinchulgwinong/domain/comment/dto/response/CommentListResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/comment/dto/response/CommentResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/comment/repository/CommentRepository.java
  src/main/java/team9502/sinchulgwinong/domain/comment/service/CommentService.java
Labels: fix

#116 fix: 띄어 쓰기 수정
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardService.java
Labels: fix

#119 fix: 최상단 광고 노출시 포인트 차감 로직 추가
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/controller/JobBoardController.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/response/JobBoardListResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/repository/JobBoardRepository.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardService.java
Labels: fix

#121 fix: 게시글 전체 조회, 내가 작성한 게시글 전체 조회 페이지 네이션 구현
  src/main/java/team9502/sinchulgwinong/domain/board/controller/BoardController.java
  src/main/java/team9502/sinchulgwinong/domain/board/dto/response/BoardListResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/board/repository/BoardRepository.java
  src/main/java/team9502/sinchulgwinong/domain/board/service/BoardService.java
Labels: fix

#122 fix: 댓글 전체 조회, 내가 작성한 댓글 전체 조회 페이지 네이션 구현
  src/main/java/team9502/sinchulgwinong/domain/comment/controller/CommentController.java
  src/main/java/team9502/sinchulgwinong/domain/comment/dto/response/CommentListResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/comment/repository/CommentRepository.java
  src/main/java/team9502/sinchulgwinong/domain/comment/service/CommentService.java
Labels: fix

#123 feat: imap을 사용하여 이메일 답신에 따라 삭제 처리
  build.gradle
  src/main/java/team9502/sinchulgwinong/domain/email/service/EmailReceiverService.java
  src/main/java/team9502/sinchulgwinong/domain/review/entity/Review.java
  src/main/java/team9502/sinchulgwinong/domain/review/entity/ReviewVisibilityRequests.java
  src/main/java/team9502/sinchulgwinong/domain/review/enums/ReviewStatus.java
  src/main/java/team9502/sinchulgwinong/domain/review/repository/ReviewRepository.java
  src/main/java/team9502/sinchulgwinong/domain/review/repository/ReviewVisibilityRequestsRepository.java
  src/main/java/team9502/sinchulgwinong/domain/review/service/ReviewService.java
  src/main/java/team9502/sinchulgwinong/domain/review/service/ReviewVisibilityRequestsService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: enhancement

#125 feature: 기업 정보 스크랩 api 추가
  src/main/java/team9502/sinchulgwinong/domain/scrap/controller/ScrapController.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/dto/response/CpUserScrapListResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/dto/response/JobScrapResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/dto/response/ScrapResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/entity/BoardScrap.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/entity/CpUserScrap.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/repository/BoardScrapsRepository.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/repository/CpUserScrapRepository.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/repository/JobScrapRepository.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/repository/ScrapsRepository.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/service/ScrapService.java
Labels: enhancement, fix

#127 배포
  src/main/java/team9502/sinchulgwinong/domain/scrap/controller/ScrapController.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/dto/response/CpUserScrapListResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/dto/response/JobScrapResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/dto/response/ScrapResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/entity/BoardScrap.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/entity/CpUserScrap.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/repository/BoardScrapsRepository.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/repository/CpUserScrapRepository.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/repository/JobScrapRepository.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/repository/ScrapsRepository.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/service/ScrapService.java
Labels: deployment

#135 fix: board 단건 조회 인증 없이 조회 가능 하도록 수정
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
Labels: fix

#128 feat: Faq CRUD + 페이지네이션
  src/main/java/team9502/sinchulgwinong/domain/faq/controller/FaqController.java
  src/main/java/team9502/sinchulgwinong/domain/faq/dto/request/FaqCreationRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/faq/dto/request/FaqUpdateRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/faq/dto/response/FaqListResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/faq/dto/response/FaqPageResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/faq/dto/response/FaqResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/faq/entity/Faq.java
  src/main/java/team9502/sinchulgwinong/domain/faq/repository/FaqRepository.java
  src/main/java/team9502/sinchulgwinong/domain/faq/repository/FaqRepositoryCustom.java
  src/main/java/team9502/sinchulgwinong/domain/faq/repository/FaqRepositoryImpl.java
  src/main/java/team9502/sinchulgwinong/domain/faq/service/FaqService.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
  src/main/java/team9502/sinchulgwinong/global/exception/ErrorCode.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
Labels: enhancement

#137 hotfix: 상태 디폴트값 수정
  src/main/java/team9502/sinchulgwinong/domain/review/entity/Review.java
Labels: enhancement

#139 fix: 게시글 검색 전체 조회 api 구현
  src/main/java/team9502/sinchulgwinong/domain/board/controller/BoardController.java
  src/main/java/team9502/sinchulgwinong/domain/board/dto/request/BoardFindRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/board/repository/BoardRepository.java
  src/main/java/team9502/sinchulgwinong/domain/board/service/BoardService.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
Labels: enhancement

#140 hotfix: 상태 디폴트값 수정
  src/main/java/team9502/sinchulgwinong/domain/review/entity/Review.java
Labels: fix

#142 배포
  src/main/java/team9502/sinchulgwinong/domain/board/controller/BoardController.java
  src/main/java/team9502/sinchulgwinong/domain/board/dto/request/BoardFindRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/board/repository/BoardRepository.java
  src/main/java/team9502/sinchulgwinong/domain/board/service/BoardService.java
  src/main/java/team9502/sinchulgwinong/domain/review/entity/Review.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
Labels: deployment

#143 fix: 기업 스크랩 생성/삭제 api 수정
  src/main/java/team9502/sinchulgwinong/domain/scrap/controller/ScrapController.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/repository/CpUserScrapRepository.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/service/ScrapService.java
Labels: fix

#144 배포
  src/main/java/team9502/sinchulgwinong/domain/scrap/controller/ScrapController.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/repository/CpUserScrapRepository.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/service/ScrapService.java
Labels: deployment

#145 fix: 오타 수정
  src/main/java/team9502/sinchulgwinong/domain/scrap/repository/CpUserScrapRepository.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/service/ScrapService.java
Labels: fix

#146 배포
  src/main/java/team9502/sinchulgwinong/domain/scrap/repository/CpUserScrapRepository.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/service/ScrapService.java
Labels: deployment

#147 feat: 기업회원 전체 조회 + 페이지네이션 + 필터링
  src/main/java/team9502/sinchulgwinong/domain/companyUser/controller/CpUserController.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/dto/response/CpUserPageResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/dto/response/CpUserResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/entity/CompanyUser.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/repository/CompanyUserRepository.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/repository/CompanyUserRepositoryCustom.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/repository/CompanyUserRepositoryImpl.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/service/CpUserService.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
Labels: enhancement

#152 fix: 게시글 응답 값 수정, 스크랩 버그 수정
  src/main/java/team9502/sinchulgwinong/domain/board/controller/BoardController.java
  src/main/java/team9502/sinchulgwinong/domain/board/dto/response/BoardResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/board/service/BoardService.java
  src/main/java/team9502/sinchulgwinong/domain/comment/repository/CommentRepository.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/repository/BoardScrapsRepository.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/repository/CpUserScrapRepository.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/repository/JobScrapRepository.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/service/ScrapService.java
Labels: fix

#153 fix: 응답값에 닉네임 추가
  src/main/java/team9502/sinchulgwinong/domain/comment/dto/response/CommentResponseDTO.java
Labels: fix

#154 fix: 구인 게시글 응답 값에 기업 이름 포함 하도록 수정
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/response/JobBoardResponseDTO.java
Labels: fix

#155 배포
  src/main/java/team9502/sinchulgwinong/domain/board/controller/BoardController.java
  src/main/java/team9502/sinchulgwinong/domain/board/dto/response/BoardResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/board/service/BoardService.java
  src/main/java/team9502/sinchulgwinong/domain/comment/dto/response/CommentResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/comment/repository/CommentRepository.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/controller/CpUserController.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/dto/response/CpUserPageResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/dto/response/CpUserResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/entity/CompanyUser.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/repository/CompanyUserRepository.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/repository/CompanyUserRepositoryCustom.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/repository/CompanyUserRepositoryImpl.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/service/CpUserService.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/response/JobBoardResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/repository/BoardScrapsRepository.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/repository/CpUserScrapRepository.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/repository/JobScrapRepository.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/service/ScrapService.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
Labels: deployment

#156 fix: 내가 작성한 구인 게시글 수정
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/controller/JobBoardController.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
Labels: fix

#157 fix: 내가 작성한 구인 게시글 인증없이 조회 되도록 수정
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/controller/JobBoardController.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
Labels: deployment

#158 feat: 내가 만든 쿠키
  src/main/java/team9502/sinchulgwinong/domain/companyUser/entity/CompanyUser.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtTokenProvider.java
Labels: enhancement

#160 fix: png, jpg, jpge, gif 확장자만 업로드 되도록 구현
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardService.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
  src/main/java/team9502/sinchulgwinong/global/exception/ErrorCode.java
Labels: fix

#161 배포
  src/main/java/team9502/sinchulgwinong/domain/companyUser/entity/CompanyUser.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardService.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
  src/main/java/team9502/sinchulgwinong/global/exception/ErrorCode.java
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtTokenProvider.java
Labels: deployment

#162 feat: 쿠키 설정 수정(secure, samesite) + 사용자 회원가입시 전화번호 수정 + 이메일 중복 가입 불가
  src/main/java/team9502/sinchulgwinong/domain/auth/service/AuthService.java
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: enhancement, fix

#163 fix: 기업 전체조회 수정
  src/main/java/team9502/sinchulgwinong/domain/companyUser/controller/CpUserController.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/repository/CompanyUserRepositoryImpl.java
Labels: fix

#164 feature: WebClient를 사용해 openAPI 를 가져오고 DB에 저장하는 API 구현
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/controller/JobBoardController.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/response/JobBoardResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/response/JobOpenApiDetailResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/response/JobOpenApiResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/response/JobOpenApiResponseVO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/entity/JobBoard.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/repository/JobBoardRepository.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardOpenApiService.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardService.java
  src/main/java/team9502/sinchulgwinong/global/config/WebClientConfig.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
Labels: enhancement, fix

#166 배포
  .github/workflows/sinChul.yml
  src/main/java/team9502/sinchulgwinong/domain/auth/service/AuthService.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/controller/CpUserController.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/repository/CompanyUserRepositoryImpl.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/controller/JobBoardController.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/response/JobBoardResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/response/JobOpenApiDetailResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/response/JobOpenApiResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/response/JobOpenApiResponseVO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/entity/JobBoard.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/repository/JobBoardRepository.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardOpenApiService.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardService.java
  src/main/java/team9502/sinchulgwinong/global/config/WebClientConfig.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
Labels: deployment

#168 fix: WebFlux 추가
  build.gradle
Labels: fix

#169 배포
  build.gradle
Labels: deployment

#170 fix: cors 수정
  src/main/java/team9502/sinchulgwinong/global/config/CorsConfig.java
Labels: fix

#171 배포
  src/main/java/team9502/sinchulgwinong/global/config/CorsConfig.java
Labels: deployment

#172 fix: 도메인 설정 추가 + 기업회원 조회수 null
  src/main/java/team9502/sinchulgwinong/domain/auth/service/AuthService.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/entity/CompanyUser.java
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: fix

#174 쿠키 + 기업회원 수정
  src/main/java/team9502/sinchulgwinong/domain/auth/service/AuthService.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/entity/CompanyUser.java
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: deployment

#175 feature: 지역 카테고리 검색 api 구현
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/controller/JobBoardController.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/request/JobBoardCategoryRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/request/JobBoardRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/request/JobBoardUpdateRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/response/JobBoardResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/entity/JobBoard.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/entity/Locality.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/repository/JobBoardRepository.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/repository/LocalityRepository.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardCategoryService.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardOpenApiService.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardService.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
Labels: enhancement, fix

#176 hotfix: 쿠키 로컬/배포 버전 분리 제발..
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: fix

#178 fix: jobBoard 카테고리api는 category 도메인으로 변경
  src/main/java/team9502/sinchulgwinong/domain/category/controller/JobBoardCategoryController.java
  src/main/java/team9502/sinchulgwinong/domain/category/dto/request/JobBoardCategoryRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/category/entity/Locality.java
  src/main/java/team9502/sinchulgwinong/domain/category/repository/LocalityRepository.java
  src/main/java/team9502/sinchulgwinong/domain/category/service/JobBoardCategoryService.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/controller/JobBoardController.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/entity/JobBoard.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardService.java
Labels: fix

#179 배포
  src/main/java/team9502/sinchulgwinong/domain/category/controller/JobBoardCategoryController.java
  src/main/java/team9502/sinchulgwinong/domain/category/dto/request/JobBoardCategoryRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/category/entity/Locality.java
  src/main/java/team9502/sinchulgwinong/domain/category/repository/LocalityRepository.java
  src/main/java/team9502/sinchulgwinong/domain/category/service/JobBoardCategoryService.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/controller/JobBoardController.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/request/JobBoardRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/request/JobBoardUpdateRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/response/JobBoardResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/entity/JobBoard.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/repository/JobBoardRepository.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardOpenApiService.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardService.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
Labels: deployment

#180 fix: jobBoard 모집 시작일 제거
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/request/JobBoardUpdateRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardService.java
Labels: fix

#181 배포
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/request/JobBoardUpdateRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardService.java
Labels: deployment

#182 hotfix: 쿠키 테스트
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: fix

#184 fix: openAPI 사용으로 localityId null 체크 추가
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/response/JobBoardResponseDTO.java
Labels: fix

#185 배포
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/response/JobBoardResponseDTO.java
Labels: deployment

#186 hotfix: 쿠키 테스트
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: fix

#188 hotfix: 쿠키 테스트
  src/main/java/team9502/sinchulgwinong/global/config/CorsConfig.java
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: fix

#189 hotfix: 쿠키 테스트
  src/main/java/team9502/sinchulgwinong/global/config/CorsConfig.java
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: deployment

#193 feature: 업종 대분류,소분류 조회 api, 업종 카테고리 검색으로 구인글 전체 조회하는 api 구현
  src/main/java/team9502/sinchulgwinong/domain/category/controller/JobBoardCategoryController.java
  src/main/java/team9502/sinchulgwinong/domain/category/dto/request/JobCategoryRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/category/dto/request/JobLocalityCategoryRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/category/entity/JobCategory.java
  src/main/java/team9502/sinchulgwinong/domain/category/repository/JobCategoryRepository.java
  src/main/java/team9502/sinchulgwinong/domain/category/service/JobBoardCategoryService.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/controller/JobBoardController.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/request/JobBoardRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/request/JobBoardUpdateRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/response/JobBoardResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/entity/JobBoard.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/repository/JobBoardRepository.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardService.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
Labels: enhancement, fix

#192 hotfix: 쿠키 테스트
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: fix

#194 배포쓰
  src/main/java/team9502/sinchulgwinong/domain/category/controller/JobBoardCategoryController.java
  src/main/java/team9502/sinchulgwinong/domain/category/dto/request/JobCategoryRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/category/dto/request/JobLocalityCategoryRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/category/entity/JobCategory.java
  src/main/java/team9502/sinchulgwinong/domain/category/repository/JobCategoryRepository.java
  src/main/java/team9502/sinchulgwinong/domain/category/service/JobBoardCategoryService.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/controller/JobBoardController.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/request/JobBoardRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/request/JobBoardUpdateRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/dto/response/JobBoardResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/entity/JobBoard.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/repository/JobBoardRepository.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardService.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: deployment

#197 hotfix: 쿠키 테스트
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: enhancement

#198 hotfix: 쿠키 테스트
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: deployment

#200 hotfix: 쿠키 테스트
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: deployment

#201 hotfix: 쿠키 테스트
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: fix

#202 hotfix: 쿠키 테스트
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: deployment

#203 hotfix: 쿠키 테스트
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: fix

#204 hotfix: 쿠키 테스트
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: deployment

#205 hotfix: 쿠키 테스트
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: fix

#207 Update sinChul.yml
  .github/workflows/sinChul.yml
Labels: deployment

#208 Update sinChul.yml
  .github/workflows/sinChul.yml
Labels: deployment

#210 Update sinChul.yml
  .github/workflows/sinChul.yml
Labels: deployment

#211 Update sinChul.yml
  .github/workflows/sinChul.yml
Labels: deployment

#212 Update sinChul.yml
  .github/workflows/sinChul.yml
Labels: deployment

#213 Update sinChul.yml
  .github/workflows/sinChul.yml
Labels: deployment

#214 Update sinChul.yml
  .github/workflows/sinChul.yml
Labels: deployment

#215 Update sinChul.yml
  .github/workflows/sinChul.yml
Labels: deployment

#217 배포
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: deployment

#218 fix: mapping RESTful 하게 수정
  src/main/java/team9502/sinchulgwinong/domain/category/controller/JobBoardCategoryController.java
Labels: fix

#219 배포
  src/main/java/team9502/sinchulgwinong/domain/category/controller/JobBoardCategoryController.java
Labels: deployment

#220 fix: 카테고리 검색 인증 필요 없도록 수정
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
Labels: fix

#221 배포
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
Labels: deployment

#227 Update sinChul.yml
  .github/workflows/sinChul.yml
Labels: deployment

#228 fix: 의존성 추가
  build.gradle
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
Labels: fix

#229 Update sinChul.yml
  .github/workflows/sinChul.yml
  build.gradle
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
Labels: deployment

#230 Update sinChul.yml
  .github/workflows/sinChul.yml
Labels: deployment

#231 Update sinChul.yml
  .github/workflows/sinChul.yml
Labels: deployment

#232 feat: 기업 회원 프로필 조회
  src/main/java/team9502/sinchulgwinong/domain/companyUser/controller/CpUserController.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
Labels: enhancement

#233 feat: 기업 회원 프로필 조회 [배포]
  src/main/java/team9502/sinchulgwinong/domain/companyUser/controller/CpUserController.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
Labels: deployment

#234 feature: 채팅 api 구현, redis 설정, websocket 설정
  build.gradle
  src/main/java/team9502/sinchulgwinong/domain/chat/controller/ChatController.java
  src/main/java/team9502/sinchulgwinong/domain/chat/dto/request/ChatRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/chat/dto/response/ChatMessageResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/chat/dto/response/ChatRoomResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/chat/entity/ChatMessage.java
  src/main/java/team9502/sinchulgwinong/domain/chat/entity/ChatRoom.java
  src/main/java/team9502/sinchulgwinong/domain/chat/repository/ChatMessageRepository.java
  src/main/java/team9502/sinchulgwinong/domain/chat/repository/ChatRoomRepository.java
  src/main/java/team9502/sinchulgwinong/domain/chat/service/ChatRoomNotification.java
  src/main/java/team9502/sinchulgwinong/domain/chat/service/ChatService.java
  src/main/java/team9502/sinchulgwinong/domain/chat/service/MessagePublisher.java
  src/main/java/team9502/sinchulgwinong/domain/chat/service/RedisSubscriber.java
  src/main/java/team9502/sinchulgwinong/global/config/RedisConfig.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSocketConfig.java
  src/main/java/team9502/sinchulgwinong/global/exception/ErrorCode.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: enhancement, fix

#235 fix: jwt 수정
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: fix

#236 배포
  build.gradle
  src/main/java/team9502/sinchulgwinong/domain/chat/controller/ChatController.java
  src/main/java/team9502/sinchulgwinong/domain/chat/dto/request/ChatRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/chat/dto/response/ChatMessageResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/chat/dto/response/ChatRoomResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/chat/entity/ChatMessage.java
  src/main/java/team9502/sinchulgwinong/domain/chat/entity/ChatRoom.java
  src/main/java/team9502/sinchulgwinong/domain/chat/repository/ChatMessageRepository.java
  src/main/java/team9502/sinchulgwinong/domain/chat/repository/ChatRoomRepository.java
  src/main/java/team9502/sinchulgwinong/domain/chat/service/ChatRoomNotification.java
  src/main/java/team9502/sinchulgwinong/domain/chat/service/ChatService.java
  src/main/java/team9502/sinchulgwinong/domain/chat/service/MessagePublisher.java
  src/main/java/team9502/sinchulgwinong/domain/chat/service/RedisSubscriber.java
  src/main/java/team9502/sinchulgwinong/global/config/JacksonConfig.java
  src/main/java/team9502/sinchulgwinong/global/config/RedisConfig.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSocketConfig.java
  src/main/java/team9502/sinchulgwinong/global/exception/ErrorCode.java
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: deployment

#237 fix: jwt 수정
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: fix

#238 배포
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: deployment

#239 Update sinChul.yml
  .github/workflows/sinChul.yml
Labels: deployment

#240 Update sinChul.yml
  .github/workflows/sinChul.yml
Labels: deployment

#241 Update sinChul.yml
  .github/workflows/sinChul.yml
Labels: deployment

#242 Update sinChul.yml
  .github/workflows/sinChul.yml
Labels: deployment

#243 fix: 레디스, 웹소켓 수정
  src/main/java/team9502/sinchulgwinong/domain/chat/service/RedisSubscriber.java
  src/main/java/team9502/sinchulgwinong/global/config/RedisConfig.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
Labels: fix

#244 배포
  .github/workflows/sinChul.yml
  src/main/java/team9502/sinchulgwinong/domain/chat/service/RedisSubscriber.java
  src/main/java/team9502/sinchulgwinong/global/config/RedisConfig.java
  src/main/java/team9502/sinchulgwinong/global/config/WebSecurityConfig.java
Labels: deployment

#245 fix: 레디스 설정 삭제, Message 매핑으로 수정, 웹소켓으로 실시간 구현하도록 수정
  src/main/java/team9502/sinchulgwinong/domain/chat/controller/ChatController.java
  src/main/java/team9502/sinchulgwinong/domain/chat/dto/response/ChatMessageResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/chat/service/ChatRoomNotification.java
  src/main/java/team9502/sinchulgwinong/domain/chat/service/ChatService.java
  src/main/java/team9502/sinchulgwinong/domain/chat/service/MessagePublisher.java
  src/main/java/team9502/sinchulgwinong/domain/chat/service/RedisSubscriber.java
  src/main/java/team9502/sinchulgwinong/global/config/RedisConfig.java
Labels: fix

#246 배포
  src/main/java/team9502/sinchulgwinong/domain/chat/controller/ChatController.java
  src/main/java/team9502/sinchulgwinong/domain/chat/dto/response/ChatMessageResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/chat/service/ChatRoomNotification.java
  src/main/java/team9502/sinchulgwinong/domain/chat/service/ChatService.java
  src/main/java/team9502/sinchulgwinong/domain/chat/service/MessagePublisher.java
  src/main/java/team9502/sinchulgwinong/domain/chat/service/RedisSubscriber.java
  src/main/java/team9502/sinchulgwinong/global/config/RedisConfig.java
Labels: deployment

#247 feat: 구직자 탈퇴
  src/main/java/team9502/sinchulgwinong/domain/companyUser/controller/CpUserController.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/dto/response/CpUserResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/service/CpUserService.java
  src/main/java/team9502/sinchulgwinong/domain/point/repository/SavedPointRepository.java
  src/main/java/team9502/sinchulgwinong/domain/point/repository/UsedPointRepository.java
  src/main/java/team9502/sinchulgwinong/domain/point/service/PointService.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/repository/BoardScrapsRepository.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/repository/CpUserScrapRepository.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/repository/JobScrapRepository.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/service/ScrapService.java
  src/main/java/team9502/sinchulgwinong/domain/user/controller/UserController.java
  src/main/java/team9502/sinchulgwinong/domain/user/dto/request/UserDeleteRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/user/entity/User.java
  src/main/java/team9502/sinchulgwinong/domain/user/service/UserService.java
  src/main/java/team9502/sinchulgwinong/global/response/SuccessCode.java
Labels: enhancement
