Repository team9502/sinchulgwinong-BE, pull requests merged in 2024-07, with the labels that each got.

#262 fix: 내가 쓴 리뷰는 공개
  src/main/java/team9502/sinchulgwinong/domain/review/service/ReviewService.java
Labels: fix

#264 fix: 내가 쓴 리뷰는 공개 [배포]
  src/main/java/team9502/sinchulgwinong/domain/review/service/ReviewService.java
Labels: deployment

#265 fix: 비공개 리뷰 제목, 내용, 평점 숨기기
  src/main/java/team9502/sinchulgwinong/domain/review/dto/response/UserReviewResponseDTO.java
Labels: fix

#268 fix: 사용자 타입과 로그인 경로 불일치 수정
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: fix

#270 배포
  src/main/java/team9502/sinchulgwinong/global/jwt/JwtAuthenticationFilter.java
Labels: deployment

#271 fix: 소셜로그인 dto 수정
  src/main/java/team9502/sinchulgwinong/domain/oauth/controller/SocialLoginController.java
  src/main/java/team9502/sinchulgwinong/domain/oauth/dto/request/SocialLoginRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/oauth/service/SocialLoginService.java
Labels: fix

#272 배포
  src/main/java/team9502/sinchulgwinong/domain/oauth/controller/SocialLoginController.java
  src/main/java/team9502/sinchulgwinong/domain/oauth/dto/request/SocialLoginRequestDTO.java
  src/main/java/team9502/sinchulgwinong/domain/oauth/service/SocialLoginService.java
Labels: deployment

#273 fix: 채팅방 예외 처리 추가, 사용자 타입 수정
  src/main/java/team9502/sinchulgwinong/domain/chat/repository/ChatRoomRepository.java
  src/main/java/team9502/sinchulgwinong/domain/chat/service/ChatService.java
  src/main/java/team9502/sinchulgwinong/global/exception/ErrorCode.java
Labels: fix

#274 배포
  src/main/java/team9502/sinchulgwinong/domain/chat/repository/ChatRoomRepository.java
  src/main/java/team9502/sinchulgwinong/domain/chat/service/ChatService.java
  src/main/java/team9502/sinchulgwinong/global/exception/ErrorCode.java
Labels: deployment

#275 fix: multipart 설정 추가
  src/main/resources/application-prod.yml
Labels: fix

#276 배포
  src/main/resources/application-prod.yml
Labels: deployment

#277 fix: sort 정렬 추가
  src/main/java/team9502/sinchulgwinong/domain/board/service/BoardService.java
  src/main/java/team9502/sinchulgwinong/domain/category/service/JobBoardCategoryService.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardService.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/service/ScrapService.java
Labels: fix

#278 배포
  src/main/java/team9502/sinchulgwinong/domain/board/service/BoardService.java
  src/main/java/team9502/sinchulgwinong/domain/category/service/JobBoardCategoryService.java
  src/main/java/team9502/sinchulgwinong/domain/jobBoard/service/JobBoardService.java
  src/main/java/team9502/sinchulgwinong/domain/scrap/service/ScrapService.java
Labels: deployment

#279 fix: 채팅 목록에 가장 최근 메세지 response 하도록 수정
  src/main/java/team9502/sinchulgwinong/domain/chat/dto/response/ChatRoomResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/chat/repository/ChatMessageRepository.java
  src/main/java/team9502/sinchulgwinong/domain/chat/service/ChatService.java
Labels: fix

#280 배포
  src/main/java/team9502/sinchulgwinong/domain/chat/dto/response/ChatRoomResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/chat/repository/ChatMessageRepository.java
  src/main/java/team9502/sinchulgwinong/domain/chat/service/ChatService.java
Labels: deployment

#282 기업회원 전체조회시 로그추가 [배포]
  src/main/java/team9502/sinchulgwinong/domain/companyUser/service/CpUserService.java
Labels: deployment

#283 fix: 채팅 메세지 내역에 유저 타입 추가
  src/main/java/team9502/sinchulgwinong/domain/chat/dto/response/ChatMessageResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/chat/entity/ChatMessage.java
  src/main/java/team9502/sinchulgwinong/domain/chat/service/ChatService.java
Labels: fix

#284 배포
  src/main/java/team9502/sinchulgwinong/domain/chat/dto/response/ChatMessageResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/chat/entity/ChatMessage.java
  src/main/java/team9502/sinchulgwinong/domain/chat/service/ChatService.java
Labels: fix

#285 fix: 구글 로그인 log 추가
  src/main/java/team9502/sinchulgwinong/domain/oauth/service/SocialLoginService.java
Labels: fix

#287 fix: 구글 로그인 try catch
  src/main/java/team9502/sinchulgwinong/domain/oauth/service/SocialLoginService.java
Labels: fix

#290 fix: 구글 로그인 오류 메시지를 더 자세히 출력하여 문제를 진단 [배포]
  src/main/java/team9502/sinchulgwinong/domain/oauth/service/SocialLoginService.java
Labels: deployment

#291 fix: 기업 전체조회
  src/main/java/team9502/sinchulgwinong/domain/companyUser/entity/CompanyUser.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/repository/CompanyUserRepositoryImpl.java
  src/main/java/team9502/sinchulgwinong/domain/companyUser/service/CpUserService.java
Labels: fix

#293 fix: 기업 전체조회
  src/main/java/team9502/sinchulgwinong/domain/companyUser/repository/CompanyUserRepositoryImpl.java
Labels: fix

#294 fix: 기업 전체조회 [배포]
  src/main/java/team9502/sinchulgwinong/domain/companyUser/repository/CompanyUserRepositoryImpl.java
Labels: fix, deployment

#297 fix: 응답값에 id 추가
  src/main/java/team9502/sinchulgwinong/domain/point/dto/response/SavedPointDetailResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/point/dto/response/UsedPointDetailResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/point/repository/SavedPointRepositoryCustomImpl.java
  src/main/java/team9502/sinchulgwinong/domain/point/repository/UsedPointRepositoryCustomImpl.java
  src/main/java/team9502/sinchulgwinong/domain/point/service/PointService.java
Labels: enhancement

#299 fix: 잔여 포인트 응답값에 추가
  src/main/java/team9502/sinchulgwinong/domain/point/dto/response/PointSummaryResponseDTO.java
  src/main/java/team9502/sinchulgwinong/domain/point/service/PointService.java
Labels: fix

#301 fix: swagger url 수정
  src/main/java/team9502/sinchulgwinong/global/config/SwaggerConfig.java
Labels: fix

#302 fix: swagger url 수정
  src/main/java/team9502/sinchulgwinong/global/config/SwaggerConfig.java
Labels: deployment

#303 fix: swagger url 타입 추가
  src/main/java/team9502/sinchulgwinong/global/config/SwaggerConfig.java
Labels: enhancement

#304 fix: swagger url 타입 추가
  src/main/java/team9502/sinchulgwinong/global/config/SwaggerConfig.java
Labels: deployment
